#!/bin/sh


sqoop job --exec customer_import;
hive -e "use pike;create table customer_web_staging ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.avro.AvroSerDe' STORED AS AVRO LOCATION '$hdfspath/pike/staging'  TBLPROPERTIES ('avro.schema.url'='$hdfspath/pike/schema/AutoGeneratedSchema.avsc');set hive.exec.dynamic.partition.mode=nonstrict;set hive.exec.max.dynamic.partitions=10000;set hive.exec.max.dynamic.partitions.pernode=10000;insert into customer_web partition(year, month, day) select *, year(from_unixtime(unix_timestamp(date_time, 'dd/MMM/yyyy:hh:mm:ss Z'))), month(from_unixtime(unix_timestamp(date_time, 'dd/MMM/yyyy:hh:mm:ss Z'))), day(from_unixtime(unix_timestamp(date_time, 'dd/MMM/yyyy:hh:mm:ss Z'))) from customer_web_staging where web_info not like '%Jakarta%';drop table customer_web_staging;"

